#!/usr/bin/env python3
"""
update_genome_clades_master.py

Synchronize genome_clades_master.tsv using the audited genome-length table.

This script NEVER attempts to infer genome lengths.

Genome lengths, source, confidence and QC status are obtained exclusively from

    genome_length_audit.tsv

which is generated by

    audit_genome_metadata.py

Author
------
Xtt Population Genomics Pipeline
"""

from __future__ import annotations

import logging

import pandas as pd

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from workflow.config.paths import (
    METADATA,
)

# ==========================================================
# Files
# ==========================================================

MASTER = METADATA / "genome_clades_master.tsv"

AUDIT = METADATA / "genome_length_audit.tsv"

# ==========================================================
# Logging
# ==========================================================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

LOGGER = logging.getLogger(__name__)

# ==========================================================
# Main
# ==========================================================


def main():

    LOGGER.info("Loading metadata...")

    metadata = pd.read_csv(
        MASTER,
        sep="\t",
    )

    audit = pd.read_csv(
        AUDIT,
        sep="\t",
    )

    # ------------------------------------------------------
    # Keep only relevant columns from audit
    # ------------------------------------------------------

    audit = audit[
        [
            "Genome",
            "Chosen_Length",
            "Chosen_Source",
            "Confidence",
            "QC_Status",
        ]
    ]

    audit = audit.rename(
        columns={
            "Chosen_Length": "Genome_Length",
            "Chosen_Source": "Genome_Length_Source",
            "Confidence": "Genome_Length_Confidence",
            "QC_Status": "Genome_QC",
        }
    )

    # ------------------------------------------------------
    # Remove previous audit-derived columns
    # ------------------------------------------------------

    metadata = metadata.drop(
        columns=[
            "Genome_Length",
            "Genome_Length_Source",
            "Genome_Length_Confidence",
            "Genome_QC",
        ],
        errors="ignore",
    )

    # ------------------------------------------------------
    # Merge
    # ------------------------------------------------------

    metadata = metadata.merge(
        audit,
        on="Genome",
        how="left",
        validate="one_to_one",
    )

    # ------------------------------------------------------
    # Reorder columns
    # ------------------------------------------------------

    preferred = [

        "Genome",

        "Genome_Length",

        "Genome_Length_Source",

        "Genome_Length_Confidence",

        "Genome_QC",

        "Clade",

    ]

    remaining = [

        c

        for c in metadata.columns

        if c not in preferred

    ]

    metadata = metadata[
        preferred + remaining
    ]

    # ------------------------------------------------------
    # Save
    # ------------------------------------------------------

    metadata.to_csv(
        MASTER,
        sep="\t",
        index=False,
    )

    LOGGER.info(
        "Metadata synchronized."
    )

    LOGGER.info(
        "Genomes: %d",
        len(metadata),
    )

    LOGGER.info(
        "QC summary:"
    )

    LOGGER.info(
        "\n%s",
        metadata["Genome_QC"]
        .value_counts(dropna=False)
        .to_string()
    )

    LOGGER.info(
        "Finished."
    )


# ==========================================================
# Entry point
# ==========================================================

if __name__ == "__main__":

    main()